### ISSUE TITLE
shared files between guest and host

### ISSUE THREAD

**Issue by txd0213** [caojoshua/MIT6.858#1]
I used your qemu shared file configuration and it worked fine.
But until I try to read and write to the database(the work directory is exactly the shared directory) in the virtual machine, it tells me that I don't have permission.
I guess that the user **permissions and users of the shared file between the host and the virtual machine do not match well**, what can I do?

**Comment by caojoshua** [comment]
Can you share repro steps? Are you working on main branch?

**Comment by txd0213** [comment]
Thanks for your reply!
I don't think the problem is really code-specific. 
I just want to know how you managed to avoid the host and virtual machine permissions issues while leveraging shared folders.

**Comment by caojoshua** [comment]
Yeah I ask for repro steps to help me better understand how you reach this issue. I don't remember running into the issue you mentioned.

**Comment by txd0213** [comment]
1. (host) boot the vm, "-fsdev local,path=/Users/txd0213/mit6858,security_model=mapped,id=fsdev0 -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=hostshare"
2. (guest) mount dir, "sudo mount -t 9p -o trans=virtio,version=9p2000.L hostshare /home/student/lab"
3. (guest) "cd /home/student/lab"
4. (guest) switch into lab3, "git checkout -b lab3 origin/lab3"
5. (guest) "make check"

finally i get permission problems

**Comment by caojoshua** [comment]
What is the output exactly of  `make check`? What are the permissions set for the shared directory? Depending on what `make check` is doing, you may need to give global write or execute permissions from the host.

**Comment by txd0213** [comment]
Your advice makes sense! I solved it.
